### ISSUE TITLE
Great code )))

### ISSUE THREAD

**Issue by gjf** [NateShoffner/Disable-Nvidia-Telemetry#1]
I really wonder how much free time the author has to develop a whole project for simple 4 lines of batch code:
schtasks /Change /TN "NvTmMon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}" /Disable
schtasks /Change /TN "NvTmRep_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}" /Disable
schtasks /Change /TN "NvTmRepOnLogon_{B2FE1952-0186-46C3-BAEC-A80AA35AC5B8}" /Disable
sc config NvTelemetryContainer start=disabled

Sure "update" possibility as well as background service (for what???) are good, but I have compiled the above mentioned code in 40 kb exe file [nVTDisabler.zip](https://github.com/NateShoffner/Disable-Nvidia-Telemetry/files/1254640/nVTDisabler.zip)
And I am pretty sure it could be even smaller.
It makes me laughing watching 548 kB portable archive (yes, the author thinks this task deserves an installer also, OMG).

**Comment by war59312** [comment]
Look.. Not everyone is as technically inclined as you. Good for you. 🥇

I for one understand that most user's don't have a clue about this stuff.

Thus, a nice tool that just works is much appreciated. Thank you! @NateShoffner 

There are plenty of other tools that also have portable versions and installers. That you could / would same the same thing about. And again. I appreciate all their hard work as well.

If you don't have anything nice to say... Well, do I really need to say?

**Comment by NateShoffner** [comment]
The new features (e.g. installer/updater) were things that had been requested by multiple people. Please use the issue tracker for constructive feedback/actual issues, thank you.
