### ISSUE TITLE
Auto-update check

### ISSUE THREAD

**Issue by THEtomaso** [NateShoffner/Disable-Nvidia-Telemetry#3]
It's kind of ironical that the latest version of your tool now tries to connect to the internet.
I'm not accusing you of user data collecting or anything.
..but when you consider the whole purpose of this software, it would most certainly be more appropriate if the auto-update check function was disabled by default.

**Comment by NateShoffner** [comment]
Not really ironic considering it's a single HTTP request (to GitHub) that can be found [here](https://github.com/NateShoffner/Disable-Nvidia-Telemetry/blob/master/DisableNvidiaTelemetry/Utilities/UpdaterUtilities.cs#L46) (remember, this is an open source project.

**Comment by THEtomaso** [comment]
The average user won't bother to examine the code like that.
They'll just notice that your tool tries to connect to the internet.
A tool aiming to protect people's privacy should NOT connect to the internet without the user's permission (which is exactly what your tool does at first launch)!
