### ISSUE TITLE
Suggestion: disable more Nvidia entries?

### ISSUE THREAD

**Issue by Gittyperson** [NateShoffner/Disable-Nvidia-Telemetry#4]
Thank you for your helpful utility. The suggestion is to add the ability to also disable other Nvidia auto-start entries, which are non-telemetry related (hopefully) and won't affect the system if disabled. The ones I can see are "profile update" checks (game-related I assume) and a desktop context menu entry, which can already be disabled in the Nvidia control panel but still leaves a remnant registry entry.

**Comment by beerisgood** [comment]
Also see this nice Script: https://gist.github.com/CHEF-KOCH/489686c18b709f064be9eb5180880b9f

**Comment by HetNeSS** [comment]
"C:\ProgramData\Nvidia" also might be interesting to check out, as well as "C:\Program Files\Nvidia Corporation\Installer2\Display.driver". Blocked all incoming and outcoming traffic for the time being, we'll see how it'll turn out later

**Comment by LaravelBen** [comment]
While we're wishing for stuff, how about a way to run shadowplay without GFE?

**Comment by NateShoffner** [comment]
@Gittyperson not really looking to over generalize the program for things unrelated to Nvidia telemetry.

@LaravelBen nope, GFE is required for ShadowPlay.
