### ISSUE TITLE
Missing Nvidia Telemetry Registry Keys

### ISSUE THREAD

**Issue by ravenise** [NateShoffner/Disable-Nvidia-Telemetry#5]
Running procmon while accessing the "help" tab in Nvidia Control Panel, you will see NVIDIA query and set the following registry entries

[HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\Global\FTS]
"EnableRID44231"=dword:00000001
"EnableRID64640"=dword:00000001
"EnableRID66610"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\NvControlPanel2\Client]
"OptInOrOutPreference"=dword:00000001

Simply clicking "help" also drops a Telemetry exe in the nvidia program file directory!  This telemetry exe will run while gaming, no matter what, even if you disable telemetry under /services, AND opt out of 'user experience' 

However, if you set the 3 "EnableRID" to 0 under FTS, no longer will you see an option in the control panel under NVIDIA HELP for any opting in or out out "participating in user experience." (it is completely removed now) No longer does NVIDIA control panel query the registry keys or drop files when you click "help." AND, Telemetry during gameplay is now also turned off permanently. Consuming less resources during gaming, speeding up performance. If you do not disable the three registry keys, telemetry will still run during gaming no matter what you do.  You can test this running "Sysinternals Process Explore" while gaming, and see the difference!

**Comment by NateShoffner** [comment]
Do you happen to have any documentation regarding the EnableRID keys or know whether they change between GFE builds etc?

As for the second key, it doesn't exist for me under HKLM, but I do see the query in procmon for the key under HKCU.

**Comment by NateShoffner** [comment]
Just tried replicating this. I'm not seeing any telemetry .exe being dropped anywhere, just NvTelemetryAPI64.dll being accessed when the help menu is clicked.

**Comment by kurtextrem** [comment]
I neither have `HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\Global\FTS` nor `HKEY_LOCAL_MACHINE\SOFTWARE\NVIDIA Corporation\NvControlPanel2\Client` in my keys (even after accessing the help menu). So I also cannot reproduce.

**Comment by NateShoffner** [comment]
Support for the "OptInOrOutPreference" key has been added in https://github.com/NateShoffner/Disable-Nvidia-Telemetry/commit/5651669e1c56d304edf21abd773208ce96bdd595.

**Comment by rugabunda** [comment]
I no longer have these keys any more, a year later; not sure if they re still useful, its possible.

**Comment by rugabunda** [comment]
bear in mind different keys for different cards; gtx 660 here
