### ISSUE TITLE
Registry still contains a path to a telemetry DDL

### ISSUE THREAD

**Issue by kurtextrem** [NateShoffner/Disable-Nvidia-Telemetry#6]
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\NvContainerLocalSystem`

under `ImagePath` there is still a telemetry DDL referenced. Replacing the whole line with:
```
"C:\Program Files\NVIDIA Corporation\NvContainer\nvcontainer.exe" -s NvContainerLocalSystem -f "C:\ProgramData\NVIDIA\NvContainerLocalSystem.log" -l 3 -d "C:\Program Files\NVIDIA Corporation\NvContainer\plugins\LocalSystem" -r -p 30000
```
works.

**Comment by kurtextrem** [comment]
Also, in the Task Scheduler there's `NvBatteryBoostCheckOnLogon`, which also runs Telemetry: `"C:\Program Files (x86)\NVIDIA Corporation\NvContainer\nvcontainer.exe" -f "C:\ProgramData\NVIDIA\NvContainerUser%dSPUser.log" -d "C:\Program Files (x86)\NVIDIA Corporation\NvContainer\plugins\SPUser" -r -l 3 -p 30000 -st "C:\Program Files (x86)\NVIDIA Corporation\NvContainer\NvContainerTelemetryApi.dll" -c` 

`-st "C:\Program Files (x86)\NVIDIA Corporation\NvContainer\NvContainerTelemetryApi.dll" -c` can be cleaned away like in the registry key.

**Comment by TheJanissaire** [comment]
Since he probably won't update it could you explain to an end user like me on how to fix that issue?Telemetry is literally nuking my computer performance in video game and making it a ramming mess.

**Comment by kurtextrem** [comment]
@TheJanissaire Regarding the registry key, open `regedit` (if you don't know how, look it up on Google) and navigate to the key in the first post. Double click `ImagePath`, copy the value in an text editor. Now remove `-st "something that ends with TelemetryApi.ddl" -c` in the editor and paste it back into the window where you've copied the value from. Click ok. 

Regarding my second comment, I went with simply disabling the task. Go to `taskschd.msc`, find `NvBatteryBoostCheckOnLogon`, right click it and choose `Deactivate`.

**Comment by kurtextrem** [comment]
@NateShoffner No, no errors/popups or anything. Have been doing it for every driver release since I've posted this issue.

And yup, seems like they removed the telemetry library from NvBatteryBoostCheckOnLogon :)
