### ISSUE TITLE
New telemetry with 397.93

### ISSUE THREAD

**Issue by alexblhr** [NateShoffner/Disable-Nvidia-Telemetry#8]
Hello
Starting with driver version 397.93 there are more telemetry services than before

Are you planning to add support for stopping them ?

**Comment by NateShoffner** [comment]
If you're referring to the tasks, yes, I'll be adding them.

**Comment by NateShoffner** [comment]
Added support for more generalized wildcard matches in https://github.com/NateShoffner/Disable-Nvidia-Telemetry/commit/45e01ff18ce906bf3c794b4d1ca9503e34238be0.
